// reference.mjs — docs/reference/ is what the code says of itself, and keeps saying it
import fs from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { REPO, ok, cli, mktmp, done } from './_h.mjs';

const gen = spawnSync(process.execPath, [path.join(REPO, 'scripts/gen-reference.mjs'), '--check'], { encoding: 'utf8', timeout: 120000 });
ok(gen.status === 0, 'reference: every page is current and every table matches the code' +
  (gen.status === 0 ? '' : ' (run: node scripts/gen-reference.mjs)\n' + (gen.stderr || '').trim()));

const page = (f) => fs.readFileSync(path.join(REPO, 'docs/reference', f), 'utf8');

// The check above compares the pages with what the generator builds; these say what the generator
// must build in the first place, so a generator that lost a section cannot pass by being consistent.
const T = mktmp();
const help = cli(['help'], { env: { HUBD_DIR: T, HUBD_TEAM_DIR: T, HUBD_NODE: 'oak' }, cwd: T }).stdout;
const commands = [...new Set([...help.matchAll(/^ {2}(\S[^\s|]*)/gm)].map(m => m[1]))];
const cliMd = page('cli.md');
ok(commands.length > 40 && commands.every(c => cliMd.includes(`\n## ${c}\n`)), `reference: cli.md has a section for each of the ${commands.length} commands in hub help`);

const server = fs.readFileSync(path.join(REPO, 'hub/index.mjs'), 'utf8');
const tools = [...new Set([...server.matchAll(/\{ name: '(hub_\w+)',/g)].map(m => m[1]))];
const mcpMd = page('mcp.md');
ok(tools.length > 40 && tools.every(t => mcpMd.includes(`\n### ${t}\n`)), `reference: mcp.md has a section for each of the ${tools.length} tools`);

const envMd = page('env.md');
const pkg = JSON.parse(fs.readFileSync(path.join(REPO, 'package.json'), 'utf8'));
const shipped = pkg.files.flatMap(function walk(f) {
  const full = path.join(REPO, f);
  if (!fs.existsSync(full)) return [];
  if (fs.statSync(full).isDirectory()) return fs.readdirSync(full).flatMap(e => walk(path.join(f, e)));
  return /\.(mjs|js|sh)$/.test(f) ? [f] : [];
});
const vars = new Set(shipped.flatMap(f => [...fs.readFileSync(path.join(REPO, f), 'utf8').matchAll(/(?<![A-Z_])(HUBD_[A-Z0-9_]+|PROJECT_HUB_DIR)\b/g)].map(m => m[1])));
ok(vars.size > 20 && [...vars].every(v => envMd.includes('`' + v + '`')), `reference: env.md names each of the ${vars.size} variables the code reads`);

ok(fs.readdirSync(path.join(REPO, 'docs/reference')).every(f => page(f).startsWith('<!-- generated by scripts/gen-reference.mjs')),
  'reference: every page says it is generated, and how to regenerate it');

ok(pkg.files.includes('docs/reference/'), 'reference: the package ships docs/reference/');
done();
